sudo g++ Abench.cpp  Load.cpp  GlobalInfo.cpp SimpleFileReader.cpp  Worker.cpp ParallelWorker.cpp Result.cpp  -lpthread  -ldl

 sudo g++ Abench.cpp  Load.cpp  GlobalInfo.cpp SimpleFileReader.cpp  Worker.cpp ParallelWorker.cpp Result.cpp ThreadPool/threadpool.cpp  -lpthread  -ldl

 sudo g++ Abench.cpp  Load.cpp  GlobalInfo.cpp SimpleFileReader.cpp  Worker.cpp ParallelWorker.cpp Result.cpp ThreadPool/threadpool.cpp  -lpthread  -ldl  -lcurl


sudo g++ Abench.cpp  Load.cpp  GlobalInfo.cpp SimpleFileReader.cpp  Worker.cpp ParallelWorker.cpp Result.cpp ThreadPool/threadpool.cpp  -lpthread  -ldl

sudo g++ Abench.cpp  Load.cpp  GlobalInfo.cpp SimpleFileReader.cpp  Worker.cpp ParallelWorker.cpp Result.cpp ThreadPool/threadpool.cpp  -lpthread  -ldl -lcurl


sudo g++ Abench.cpp  Load.cpp  GlobalInfo.cpp PiemonQueryScanner.cpp   Worker.cpp ParallelWorker.cpp Result.cpp ThreadPool/threadpool.cpp  -lpthread  -ldl -lcurl

sudo g++ Abench.cpp  Load.cpp  GlobalInfo.cpp PiemonQueryScanner.cpp  PiemonRunner.cpp SyncPiemonRunner.cpp  Result.cpp ThreadPool/threadpool.cpp  -lpthread  -ldl -lcurl


sudo g++ Abench.cpp  Load.cpp  PiemonCache.cpp  PiemonQueryScanner.cpp  PiemonRunner.cpp SyncPiemonRunner.cpp  Result.cpp ThreadPool/threadpool.cpp  -lpthread  -ldl -lcurl

sudo g++ Abench.cpp  PiemonSchedule.cpp  PiemonCache.cpp  PiemonQueryScanner.cpp  PiemonRunner.cpp SyncPiemonRunner.cpp PiemonPerfCollector.cpp  ThreadPool/threadpool.cpp  -lpthread  -ldl -lcurl

sudo g++ Piemon.cpp  PiemonSchedule.cpp  PiemonCache.cpp  PiemonQueryScanner.cpp  PiemonRunner.cpp SyncPiemonRunner.cpp PiemonPerfCollector.cpp  ThreadPool/threadpool.cpp  -lpthread  -ldl -lcurl -o Piemon
